name: "Tweet"
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python3 src/main.py
