name: "Tweet"
on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 9 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
      dryRunEnabled:
        description: 'Whether the dry run module is enabled or not'
        required: true
        type: boolean
        default: 'false'
jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      TWITTER_USER_NAME: ${{ secrets.TWITTER_USER_NAME }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      DRY_RUN_ENABLED: ${{ github.event.inputs.dryRunEnabled }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python3 src/main.py
